config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  resources :users, only: [:index, :edit, :show, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :image  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit, :update]



  def new
    @book = Book.new
    @book = current_user.books.build
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "Book was successfully create."
       redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end


  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
       flash[:notice] = "Book was successfully updated."
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

   private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
     redirect_to books_path
    end
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit]

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(current_user)
    else
      render :edit
    end
  end

   private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
     redirect_to user_path(current_user)
    end
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_info.html.erb
<div class="container">
  <div class="row">
    <div class="col-3" style="background-color: white">
      <h1>User info</h1>
      <%= image_tag current_user.get_profile_image(100,100) %>
        
      <table class="table-hover">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= current_user.name %></td>
  　       </tr>
  　       <tr>
          　<td>introduction</td>
          　<td><%= current_user.introduction %></td>
  　       </tr>
        </tbody>
  　 　</table>
  　   <%= link_to "編集", edit_user_path(current_user.id) %>
　</div>
</div>






<h1>New book</h1>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4>Title</h4>
    <%= f.text_field :title %>
  <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
<% end %>

app/views/books/_new.html.erb
<h2>New book</h2>

    <%= form_with model: book do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title, style: "width:100%" %>
      <h4>Opinion</h4>
        <%= f.text_area :body, style: "width:100%" %>
      <nav>
        <%= f.submit 'Create Book', class: "col-xs-3 btn-sm btn-success"%>
      </nav>
    <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
    
<div class="box1">
  <h2>Editing Book</h2>
    <%= form_with model: @book do |f| %>
      <h5>Title</h5>
        <%= f.text_field :title,class:"col-xs-12" %>
      <h5>Opinion</h5>
        <%= f.text_area :body,class:"col-xs-12" %>
      <nav>
      <%= f.submit "Update Book",class: "col-xs-12 btn btn-primary" %>
      </nav>
    <% end %>
    
    <p>
    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
    </p> 
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class= "col-md-3">
      <table class="table table-user">
        <h2>User info</h2>

        <thed>
          <tr>
            <%= image_tag current_user.get_profile_image(100,100) %>
          </tr>
        </thed>

        <tbody>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>

          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <button type="button" class="btn btn-secondary btn-block text-white ">
        <%= link_to edit_user_path(current_user), class: "btn btn-secondary text-white" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </button>





      <h2>New book</h2>

      <%= form_with model: @book do |f| %>

      <h5>Title</h5>
        <%= f.text_field :title, style: "width:100%" %>
      <h5>Opinion</h5>
        <%= f.text_area :body, style: "width:100%" %>
      <nav>
        <%= f.submit 'Create Book', class: "col-xs-3 btn-sm btn-success"%>
      </nav>
      <% end %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <th>image</th>
          <th>title</th>
          <th colspan="3">Opinion</th>
        </tr>


        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %></td>
              <% end %>
          <td><%= link_to book.title, "/books/#{book.id}" %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class= "col-md-3">
      <%= render 'users/info', user:@user %>
      <%= render 'books/new', book:@newbook %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <td>
            <%= link_to user_path(@book.user_id) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %>
                <nav>
                  <%= @book.user.name %>
                </nav>
            <% end %>
          </td>

          <td><%= link_to @book.title %></td>
          <td><%= @book.body %></td>

          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn-sm btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book.id), class:"btn-sm btn-danger", method: :delete,data: {confirm: "Are you sure？"} %></td>
          <% end %>
        </tr>
      </table>
    </div>

app/views/homes/about.html.erb
<div class="text-center">
  <h1>Welcom to<i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
	  <div class="mx-auto">
	    <div class="text-center">
		    <h1>Welcom to <i class="fas fa-book"></i>Bookers!!</h1>
		    <p>In<i class="fas fa-book"></i><strong>Bookers</strong></p>
		    <p>you can share and exchange your opinions , inpresiions , and emotions</p>
		  	<p>about various books!</p>


	      <button type="button" class="btn btn-primary w-50 mt-3 mb-0">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-primary" %>
	      </button>

	      <button type="button" class="btn btn-success w-50 mt-3 mb-0">
	        <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success" %>
	      </button>
	    </div>
	  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

　　<script src="https://kit.fontawesome.com/add29eec17.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand " href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>

              <li class="nav-item">
                <%= link_to user_path(current_user), class: "text-light" do %>
                  <i class="fas fa-home"></i><span>Home</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to users_path, class: "text-light" do %>
                  <i class="fas fa-users"></i><span>Users</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to books_path, class: "text-light" do %>
                  <i class="fas fa-book-open"></i><span>Books</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "text-light" do %>
                  <i class="fas fa-sign-out-alt"></i><span>Log out</span>
                <% end %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: "text-light" do %>
                  <i class="fas fa-home"></i><span>Home</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to home_about_path, class: "text-light" do %>
                  <i class="fas fa-link"></i><span>About</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_registration_path, class: "text-light" do %>
                <i class="fas fa-user-plus"></i><span>Sign up</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_session_path, class: "text-light" do %>
                <i class="fas fa-sign-in-alt"></i><span>Log in</span>
                <% end %>
              </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>



    <main>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    <%= yield %>
    </main>

    <footer class="foooter">
      <div class="container text-center">
        <p>CopyRight Infratop.inc</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<table class="table table-user">
  <h2>User info</h2>

  <thead>
   <tr>
    <%= image_tag user.get_profile_image(100,100) %>
   </tr>
  </thead>

  <tbody>
   <tr>
     <th>name</th>
     <th><%= user.name %></th>
   </tr>

   <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
   </tr>
  </tbody>
</table>
<button type="button" class="btn btn-secondary btn-block text-white">
  <%= link_to edit_user_path(user.id), class: "btn btn-secondary text-white" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</button>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="box2">
  <h2>User info</h2>

   <%= form_with model: @user do |f| %>

    <h4>Name</h5>
    <%= f.text_field :name %>
    <h5>Image</h5>
    <%= f.file_field :profile_image %>
    <h5>Introduction</h5>
    <%= f.text_area :introduction %>

    <%= f.submit "Update User" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class= "col-md-3">
      <%= render 'users/info', user:@user %>
      <%= render 'books/new', book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>

        <% @users.each do |user| %>
        <tr class="new-table">
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user:@user %>
      <%= render 'books/new', book:@book %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <th></th>
          <th>Title</th>
          <th colspan="3">Opinion</th>
        </tr>

        <% @user.books.each do |book| %>
        <tr>
          <td><%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(100,100) %></td>
              <% end %>
          <td><%= link_to book.title, "/books/#{book.id}" %></td>
          <td><%= book.body %></p></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>